/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kafka;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void appHasAGreeting() {
    assertNotNull("A");
  }
}
